stages:
  - build

build:
  stage: build
  tags:
    - build-server-android-app-docker-ndk-r17b
  script:
    - curl -sL https://deb.nodesource.com/setup_12.x | bash -
    - apt-get install -y nodejs
    - npm install -g grunt-cli
    - npm install
    - npm run eslint
    - npm run build
