version: 2.0
workflows:
  version: 2
  build:
    jobs:
      - node10
      - node12
jobs:
  node10:
    working_directory: ~/webserver-frontend
    docker:
      - image: node:10.16.0
    steps:
      - checkout
      - run: npm install
      - run: npm run eslint

  node12:
    working_directory: ~/webserver-frontend
    docker:
      - image: node:12.4.0
    steps:
      - checkout
      - run: npm install
      - run: npm run eslint
