module.exports = {
  scarlett1: require('./scarlett-1').default,
  kim1: require('./kim-1').default,
  elon1: require('./elon-1').default,
  tom1: require('./tom-1').default,
  tom2: require('./tom-2').default,
  tom3: require('./tom-3').default,
  tom4: require('./tom-4').default,
  hiddleston1: require('./hiddleston-1').default,
  hiddleston2: require('./hiddleston-2').default,
  hiddleston3: require('./hiddleston-3').default,
  hiddleston4: require('./hiddleston-4').default,
  hiddleston5: require('./hiddleston-5').default,
  hemsworth1: require('./hemsworth-1').default,
  hemsworth2: require('./hemsworth-2').default,
  renner1: require('./renner-1').default,
  renner2: require('./renner-2').default,
  cumberbatch1: require('./cumberbatch-1').default,
  cumberbatch2: require('./cumberbatch-2').default,
  cumberbatch3: require('./cumberbatch-3').default,
  cumberbatch4: require('./cumberbatch-4').default,
  rocket1: require('./rocket-1').default,
  thanos1: require('./thanos-1').default
};
