const FastestFormikValidator = require('./FastestFormikValidator');
const _ = require('../../languages');

module.exports = new FastestFormikValidator({
  messages: {
    array: _('validation-array'),
    arrayContains: _('validation-arrayContains'),
    arrayEmpty: _('validation-arrayEmpty'),
    arrayEnum: _('validation-arrayEnum'),
    arrayLength: _('validation-arrayLength'),
    arrayMax: _('validation-arrayMax'),
    arrayMin: _('validation-arrayMin'),
    birthday: _('validation-birthday'),
    boolean: _('validation-boolean'),
    countryCode: _('validation-countryCode'),
    date: _('validation-date'),
    dateMax: _('validation-dateMax'),
    dateMin: _('validation-dateMin'),
    email: _('validation-email'),
    forbidden: _('validation-forbidden'),
    function: _('validation-function'),
    number: _('validation-number'),
    numberEqual: _('validation-numberEqual'),
    numberInteger: _('validation-numberInteger'),
    numberMax: _('validation-numberMax'),
    numberMin: _('validation-numberMin'),
    numberNegative: _('validation-numberNegative'),
    numberNotEqual: _('validation-numberNotEqual'),
    numberPositive: _('validation-numberPositive'),
    required: _('validation-required'),
    string: _('validation-string'),
    stringAbortSpecialCharacters: _('validation-stringAbortSpecialCharacters'),
    stringAcceptSpecialCharacters: _('validation-stringAcceptSpecialCharacters'),
    stringContains: _('validation-stringContains'),
    stringContainsLowerCaseLatter: _('validation-stringContainsLowerCaseLatter'),
    stringContainsNumber: _('validation-stringContainsNumber'),
    stringContainsUpperCaseLatter: _('validation-stringContainsUpperCaseLatter'),
    stringEmpty: _('validation-stringEmpty'),
    stringEnum: _('validation-stringEnum'),
    stringLength: _('validation-stringLength'),
    stringMax: _('validation-stringMax'),
    stringMin: _('validation-stringMin'),
    stringPattern: _('validation-stringPattern'),
    url: _('validation-url')
  }
});
